// generated by stringer -type=Status; DO NOT EDIT

package main

import "fmt"

const statusName = "StatusRedStatusSilverStatusGold"

var statusIndex = [...]uint8{0, 9, 21, 31}

func (i Status) String() string {
	if i < 0 || i >= Status(len(statusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return statusName[statusIndex[i]:statusIndex[i+1]]
}
